### ISSUE TITLE
Possible Updates

### ISSUE THREAD

**Issue by superwfox** [zimzaza4/GeyserUtils#5]
After putting the latest release into my extensions it booms

server:1.20.6 purpur
geyser: 2.3.2-SNAPSHOT (git-master-18ad652)
![IMG_3639](https://github.com/zimzaza4/GeyserUtils/assets/65709399/1343b519-13f4-4360-8924-745cad0d1612)

**Comment by zimzaza4** [comment]
暂时的解决办法 用独立版

**Comment by superwfox** [comment]
大哥有木有啥QQ交流群哇 这样也方便🌹

**Comment by zimzaza4** [comment]
) 我甚至不知道你从哪知道的这个

**Comment by superwfox** [comment]
EP告诉我的zim 然后我的一个朋友早六发了我这个链接 awa

**Comment by superwfox** [comment]
amazing哇 可以正常开了 tyvm🌹

**Comment by superwfox** [comment]
![IMG_1441](https://github.com/zimzaza4/GeyserUtils/assets/65709399/88ea2a12-8576-4644-a02b-502847813f1a)
java进服提示截流是因为没有改startgamepacket吗

**Comment by zimzaza4** [comment]
）这个的话，你就反馈错地方了
而且StartGamePacket 是BE的说法吧

**Comment by superwfox** [comment]
嗯嗯 他这个是微软账户的问题

对了 佬 怎么调用这个api有example看看吗 🌹

**Comment by superwfox** [comment]
我太需要/camera运镜了

**Comment by zimzaza4** [comment]
）huh 我只能说没空给example

**Comment by zimzaza4** [comment]
但这有一个

**Comment by zimzaza4** [comment]
https://github.com/zimzaza4/BetterBedrockThirdPerson

**Comment by superwfox** [comment]
嗯？！
什么是更好的第三人称
完成的/camera吗💦

**Comment by zimzaza4** [comment]
) 命令/tr
跨肩视角

**Comment by zimzaza4** [comment]
命令是没有的

**Comment by superwfox** [comment]
awa 我用cb写过一个类似的

那可以注册一个命令来还原吗

**Comment by zimzaza4** [comment]
当然可以 如果你能的话

**Comment by zimzaza4** [comment]
) 这个API 最初抄的是pnx的
所以和Geyser 本身的有些，长的不一样

**Comment by superwfox** [comment]
😂看来难度不一般捏 但是我说这话是想知道佬 能不能抽时间把这破活给整好了 thanks a lot

**Comment by zimzaza4** [comment]
显然没有 准高三了

**Comment by superwfox** [comment]
诶 那我是你学长😂
我刚刚考完

**Comment by superwfox** [comment]
早睡了 宝宝 不冲浪力 我也好好学一下je怎么个开发法 佬可否指点一二

**Comment by zimzaza4** [comment]
) 叫EP给你我QQ
